spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://47.97.214.219:3306/simple?useUnicode=true&characterEncoding=utf8
        username: cx
        password: 1

    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true